### ISSUE TITLE
Incorrect Hadamard visualisation trace

### ISSUE THREAD

**Issue by bohemian-miser** [kherb27/Blochy#4]
The Hadamard gate is a rotation around X+Z, the trace of this tool shows it moving directly from |0> to |+> and when applied again, the trace goes to |1> and then back up after a quarter turn. It should be a circle on the surface of the bloch sphere and not go into the other hemisphere. 

*First application of H*
![2024-3-8_13- 19-9](https://github.com/kherb27/Blochy/assets/158785140/6f1f387f-4d9b-45eb-9724-45f429679395)

*Second application of H*
![2024-3-8_13- 19-13](https://github.com/kherb27/Blochy/assets/158785140/851e7916-6c29-4000-85a3-32c63206931f)

*Expected result*
![](https://i.stack.imgur.com/9kbe3.png)

**Comment by kherb27** [comment]
Thank you very much for this bug report. I fixed the Hadamard gate to perform a rotation around the x+z axis.

![grafik](https://github.com/kherb27/Blochy/assets/84564621/f0b6653b-7617-4efb-9b0f-45b519d46fce)
